# Generated by Django 3.2.2 on 2021-05-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_me', '0002_answer_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateanswer',
            name='rating',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ratequestion',
            name='rating',
            field=models.BooleanField(default=True),
        ),
    ]
