# Generated by Django 3.2.2 on 2021-05-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_me', '0003_auto_20210510_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
